### ISSUE TITLE
paxschedule.com no longer exists

### ISSUE THREAD

**Issue by remyjette** [ifish12/PAX-Schedule-Creator#3]
paxschedule.com now returns NXDOMAIN. Are you planning on re-hosting it before PAX East 2016?

If not, would you have any problem with me registering the domain and hosting this code?

**Comment by mtfurlan** [comment]
Hey remyjette, we stopped hosting it because we went broke what with attending uni, if you want to host it that would be great!
The one problem is that you would need to get the schedule.xml from the people running pax, and confirm that the parser still works.
I can try to contact them next week, and we can work on updating the site for this year.

**Comment by ifish12** [comment]
Hey! Today I emailed Penny Arcade and the old method for getting the XML isn't what we have access to anymore, sadly. They use XLS Imports now, which we're not prepared to support, and I'm not even sure if we can. 

The XML method isn't going to be maintained, but what I can do is: a few days before the event, get the XML and send it your way. I'd love if you bought the domain and hosted the code for us. 

Though just don't take our names off, of course. 

Also I could email you the XMLs through the email on your Github profile.

**Comment by remyjette** [comment]
I own the domain now and have hosting - yeah I checked into it too... since they aren't doing the XML imports I just have the domain redirect to the normal schedule for now :(

I plan on rewriting it, probably using guidebook's JSON-based API, but unfortunately I won't have time to do so before PAX East in two weeks...will probably be a summer project so it's ready for Prime/West. If you do have a way to get the XML for East, though, I'll throw it up on my server so we can have it for this event. Lemme know! And of course, your names will stay credited :)

**Comment by mtfurlan** [comment]
We can't get the xml, but we will have fucking xls, that we can maybe
convert into an appropriate xml? Or just hack together a temp parser for
this year, and use the guidebook api in the future.
Using the guidbook api will be so much better, as they kept changing parts
of how the XML file worked.

**Comment by ifish12** [comment]
Mark is wrong, we can get the XML. David Coffman will still generate it for us. But I'm gonna wait until a day or two before the event so you can use it and have it be mostly updated information. 

Also I didn't know Guidebook had an API, that sounds interesting. I don't quite have the time to update it as I work full time and go to college. But if you do rewrite it, I look forward to seeing it. 

Also we can convert XLS to XML, but the way PA does it now is the the XLS directly into the guidebook backend. It's not online anymore, so we'd still have to have us manual, my update it. 

Also mark and I both have old hacks to parse the HTML schedule, we could publis those again in the meantime. Mine was written in Ruby, Mark's in Perl
